# Generated by Django 5.0.2 on 2024-02-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email_alter_user_id_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='is_staff',
        #     field=models.BooleanField(default=False, null=False),
        # ),
    ]
